// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dirsyncmap} from '../models';

export function PreviewSync(arg1:string,arg2:string):Promise<dirsyncmap.DirSyncStruct>;

export function SelectDirectory(arg1:string):Promise<string>;
