// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lsync} from '../models';

export function PreviewSync(arg1:string,arg2:string):Promise<lsync.SyncPreview>;

export function PreviewSyncAsync(arg1:string,arg2:string):Promise<lsync.SyncPreview>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SyncWithPreview(arg1:string,arg2:string,arg3:lsync.SyncPreview,arg4:boolean):Promise<void>;
