// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sync} from '../models';

export function PreviewSync(arg1:string,arg2:string):Promise<sync.SyncPreview>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SyncWithPreview(arg1:string,arg2:string,arg3:sync.SyncPreview,arg4:boolean):Promise<void>;
