// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PreviewSync(arg1, arg2) {
  return window['go']['backend']['App']['PreviewSync'](arg1, arg2);
}

export function PreviewSyncAsync(arg1, arg2) {
  return window['go']['backend']['App']['PreviewSyncAsync'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['backend']['App']['SelectDirectory'](arg1);
}

export function SyncWithPreview(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['SyncWithPreview'](arg1, arg2, arg3, arg4);
}
